services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    platform: linux/amd64
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${DB_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
      MONGO_INITDB_DATABASE: '${DB_DATABASE}'
      TZ: 'GMT'
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - db_data:/data/db # Persist data

volumes:
  db_data:
    driver: local
