import { UserEntity } from 'modules/user/domain/entities/user.entity';

import type { CreateUserDto } from '../dtos/create-user.dto';

export class UserMapper {
  static toDomain(createUserDto: CreateUserDto): UserEntity {
    return new UserEntity({
      id: '', // This will be generated by the database
      displayName: createUserDto.displayName,
      password: createUserDto.password,
      email: createUserDto.email,
      createdAt: '' as unknown as Date, // Assuming the database will handle this
      updatedAt: '' as unknown as Date, // Assuming the database will handle this
    });
  }
}
